### ISSUE TITLE
PMD annotations are added in an (Unknown event) in a (Unnamed workflow) when used in a pull request build

### ISSUE THREAD

**Issue by n-peugnet** [jwgmeligmeyling/pmd-github-action#2]
Hi, I tried to use your action but I found a bug on `pull_request` builds. It took me [some builds](https://github.com/PolyProcessInterface/ppi/actions) to find out that the action was correctly reporting violations but not on the correct build.

On [my last attempt](https://github.com/PolyProcessInterface/ppi/runs/776418159?check_suite_focus=true) tried to use [this option](https://github.com/actions/checkout#Checkout-HEAD) of the checkout action but strangely the check was still [added to the merge commit](https://github.com/PolyProcessInterface/ppi/actions/runs/137169818) :
```yaml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.event.pull_request.head.sha }}
```

I looked a little bit at your code and I wonder if using `context.ref` when the check is created instead of `context.sha` would solve this problem (when the above option is set in the checkout action).

**Comment by jwgmeligmeyling** [comment]
Hi, I noticed this myself too (see the same issue here as well: https://github.com/jwgmeligmeyling/spotbugs-github-action/issues/2 ).

I don't think this action should be used on the `pull_request` event. This is because the pull request executes against a merge commit, and the line numbers for this merge commits will be incorrect. So the annotations would be put in the wrong place if `github.event.pull_request.head.sha` were used. 

I am just going to encourage users to use the `pull` event instead and add an event based filter to the example configuration.

**Comment by jwgmeligmeyling** [comment]
For example;

```yaml
      - uses: jwgmeligmeyling/spotbugs-github-action@master
         if: ${{ github.event_name == 'push' }}
         with:
           path: '**/spotbugsXml.xml'

       - uses: jwgmeligmeyling/pmd-github-action@master
         if: ${{ github.event_name == 'push' }}
         with:
           path: '**/pmd.xml'

       - uses: jwgmeligmeyling/checkstyle-github-action@master
         if: ${{ github.event_name == 'push' }}
         with:
           path: '**/checkstyle-result.xml'
```

**Comment by n-peugnet** [comment]
> I don't think this action should be used on the `pull_request` event. This is because the pull request executes against a merge commit, and the line numbers for this merge commits will be incorrect.

In fact when I add the above `ref` parameter to the checkout action the test are not run on a merge commit but on the real HEAD of the pull request. This way the line numbers are correct. So with the fix mentioned on the other repo it would be perfect. The checkout action `ref` parameter could be added in the documentation.

You can see on [this build](https://github.com/PolyProcessInterface/ppi/pull/69/checks?check_run_id=776655077) that both `push` and `pull_request` event correctly built against the correct HEAD commit: https://github.com/PolyProcessInterface/ppi/pull/69/commits/670f31b0c717f37f7d344d5d54406c189e7bb2c5

**Comment by jwgmeligmeyling** [comment]
Yes allright, but it defeats the purpose of a build on the `pull_request` event: most users will use this event to verify that the changes are still OK after merging into master. So I could point users to that option in the documentation, but it won't be one size fits all...

I by the way cant use the `ref` either: that will be the branch name , which can't be use to push the check result to through the API.

**Comment by n-peugnet** [comment]
Yes this is why I made two jobs, one for the tests on the results of the merge and one for the codestyle on the head of the pull request. But I don't want to trigger this action on each push on every branch. I want to keep the trigger only on pull requests to master.

I mean, as you said, running this type of checks on a merge does not make a lot of sense but the reason why I run them on the pull request is only to limit to limit the number of builds.

**Comment by jwgmeligmeyling** [comment]
So then you're suggestion would be to document these two approaches in the README?

Or would you still see a way to properly handle this programatically?

**Comment by n-peugnet** [comment]
First, if we want to make this action work on pull request builds, the fix you mentioned in the linked issue must be added :
```typescript
let sha = github.context.sha

if (github.context.payload.pull_request) {
    sha = github.context.payload.pull_request.head.sha
}
```

Then you should add a warning in the readme that if someone wants to run this action on the pull request event but check on the HEAD instead of the merge, the following option should be added to the checkout action.
```yaml
- uses: actions/checkout@v2
  with:
    ref: ${{ github.event.pull_request.head.sha }}
```
